### ISSUE TITLE
Take the path and replace the PATH_TO_EXE with the path to the .exe that was just created in the mine.rs？

### ISSUE THREAD

**Issue by fuhua898** [BenjaSOL/ore-cli-gpu#2]
which path？
Is the path here the compiled path or windows.exe in the project?

**Comment by BenjaSOL** [comment]
Yes the .exe that is created copy the path to that and replace PATH_TO_EXE 

Example: 

C:\\home\\ore-cli-gpu\\windows.exe

**Comment by fuhua898** [comment]
> Yes the .exe that is created copy the path to that and replace PATH_TO_EXE
> 
> Example: Make sure you use two \ on windows "C:\home\ore-cli-gpu\windows.exe"

![image](https://github.com/BenjaSOL/ore-cli-gpu/assets/73608169/7b874952-7c03-4d81-8b85-cd642e21c01e)
Every step is correct, but why

**Comment by Kokiiez** [comment]
Run as admin

**Comment by fuhua898** [comment]
> Run as admin

Maybe I'm just using the admin run but still

**Comment by guilinzys2016** [comment]
> > Run as admin
> 
> Maybe I'm just using the admin run but still

If you use Linux:
```shell
chmod +x YOUR_PATH_TO_EXE
```
