### ISSUE TITLE
nonce_worker failed to spawn

### ISSUE THREAD

**Issue by mainframer** [BenjaSOL/ore-cli-gpu#3]
Mining for a valid hash...
Calling find_next_hash_par
thread 'main' panicked at src/mine.rs:175:6:
nonce_worker failed to spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I was running on Ubuntu 20.0 with RTX 4090.

**Comment by OwenLittleWhite** [comment]
same error with you, and I'm using the absolute path

**Comment by BenjaSOL** [comment]
@mainframer @OwenLittleWhite I am working on this at the moment should have the fix for Linux soon.

**Comment by OwenLittleWhite** [comment]
> @mainframer @OwenLittleWhite I am working on this at the moment should have the fix for Linux soon.

It's my fault, I type a wrong path. When recompile, I can run it! Thanks a lot, and looking forward to the new version

**Comment by niu12503** [comment]
> @mainframer @OwenLittleWhite I am working on this at the moment should have the fix for Linux soon.

need windows please thx

**Comment by BenjaSOL** [comment]
> > @mainframer @OwenLittleWhite I am working on this at the moment should have the fix for Linux soon.
> 
> need windows please thx

Windows should work fine if your paths are correct.

**Comment by BenjaSOL** [comment]
> Mining for a valid hash... Calling find_next_hash_par thread 'main' panicked at src/mine.rs:175:6: nonce_worker failed to spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" } note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> I was running on Ubuntu 20.0 with RTX 4090.

Make sure you use the executable path.
