### ISSUE TITLE
keys_file_path error

### ISSUE THREAD

**Issue by aa66609** [BenjaSOL/ore-cli-gpu#4]
thread 'main' panicked at src/main.rs:249:59:
called `Result::unwrap()` on an `Err` value: Error("Is a directory (os error 21)", line: 0, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by BenjaSOL** [comment]
Make sure you use the keypair json file and the executable path for the CUDA file.

**Comment by aa66609** [comment]
![image](https://github.com/BenjaSOL/ore-cli-gpu/assets/13633514/c2be8edb-9add-4b44-852a-cf457e92720a)

我看出錯是路徑有問題，但我輸入的指令確實是私鑰路徑，而且如果我測試輸入單一個睡能進入miner執行的

**Comment by BenjaSOL** [comment]
> ![image](https://private-user-images.githubusercontent.com/13633514/322371580-3989b2a4-a0f8-498f-9331-a0a948e05d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjI4ODMsIm5iZiI6MTcxMzE2MjU4MywicGF0aCI6Ii8xMzYzMzUxNC8zMjIzNzE1ODAtMzk4OWIyYTQtYTBmOC00OThmLTkzMzEtYTBhOTQ4ZTA1ZDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA2Mjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZTFjNjhmYmUxMWY0Y2YwM2NjNWNkMDk3MzEwYjA1YTBjNTZhOTdmZWQxODIxZDRmZmY4Y2ZjOTA0YWIzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EhETa6IMtYfQbgjC46pR-ZEBn74JrX9YKqHzRbQn4_w)
> 
> 我看出錯是路徑有問題，但我輸入的指令確實是私鑰路徑，而且如果我測試輸入單一個key是能進入miner執行的

Yes that is correct.

**Comment by aa66609** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13633514/322371580-3989b2a4-a0f8-498f-9331-a0a948e05d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjI4ODMsIm5iZiI6MTcxMzE2MjU4MywicGF0aCI6Ii8xMzYzMzUxNC8zMjIzNzE1ODAtMzk4OWIyYTQtYTBmOC00OThmLTkzMzEtYTBhOTQ4ZTA1ZDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA2Mjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZTFjNjhmYmUxMWY0Y2YwM2NjNWNkMDk3MzEwYjA1YTBjNTZhOTdmZWQxODIxZDRmZmY4Y2ZjOTA0YWIzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EhETa6IMtYfQbgjC46pR-ZEBn74JrX9YKqHzRbQn4_w)
> > 我看出錯是路徑有問題，但我輸入的指令確實是私鑰路徑，而且如果我測試輸入單一個key是能進入miner執行的
> 
> Yes that is correct.

but still get this error
![image](https://github.com/BenjaSOL/ore-cli-gpu/assets/13633514/b8b506ce-d414-4633-b6e7-46302828c89a)
