### ISSUE TITLE
linux ubuntu报错

### ISSUE THREAD

**Issue by lusiwei** [BenjaSOL/ore-cli-gpu#5]
![image](https://github.com/BenjaSOL/ore-cli-gpu/assets/32103164/aa9c9db8-6eba-4383-b70f-ff1e46e5837e)

**Comment by BenjaSOL** [comment]
Try the new linux.cu file and let me know if you still get that error.

**Comment by lusiwei** [comment]
![image](https://github.com/BenjaSOL/ore-cli-gpu/assets/32103164/098036e2-4893-40e6-8c55-89c2e5f62094)

**Comment by BenjaSOL** [comment]
I'm unable to replicate,  it builds perfectly on my system. I would share the executables but most people don't trust that so I didn't add it, if you would like me to add them please let me know.

I also only changed a couple of lines so that shouldn't have been an issue.

**Comment by Kokiiez** [comment]
please share exe

**Comment by MatthiasT91** [comment]
> Try the new linux.cu file and let me know if you still get that error.

How to run this? Lost in the sauce with the linux.cu

**Comment by Rai4over** [comment]
please share exe thank u

**Comment by BenjaSOL** [comment]
> > Try the new linux.cu file and let me know if you still get that error.
> 
> How to run this? Lost in the sauce with the linux.cu

Follow the rea me just run the command and use the executable that's created

**Comment by BenjaSOL** [comment]
I have added the executable to the releases.
